### ISSUE TITLE
Cannot resolve symbol 'lwjgl'

### ISSUE THREAD

**Issue by SongRunqi** [Appu26J/Softuninstall#1]
I forked your project and clone it to my cp. And after that I opened the SoftUnistall.java, in line 7~9 and 14~16, my ide prompts Cannot resolve symbol 'lwjgl'.
just like this:
![image](https://github.com/Appu26J/Softuninstall/assets/150511635/ec1273a7-dcd7-4793-997a-7318b48a078b)
How can I deal that?

**Comment by SongRunqi** [comment]
The library really in my dir
![image](https://github.com/Appu26J/Softuninstall/assets/150511635/194c7c0a-ad04-433b-acdc-b0c95c2256d5)

**Comment by Appu26J** [comment]
that's strange (i guess libraries are pc specific), try adding the library folder into your project

**Comment by Appu26J** [comment]
<img width="256" alt="image" src="https://github.com/Appu26J/Softuninstall/assets/128838345/96eeaf54-e09a-4d01-a38c-f79aae1222d3">

right click on the libraries folder and click the "Add as Library" button

**Comment by SongRunqi** [comment]
ok, I did it! I run it successfully, but there seems something wrong with the program. Some item with no name, and When I click the uninstall icon, it just no actions.
![image](https://github.com/Appu26J/Softuninstall/assets/150511635/5dbfecf7-790d-460a-a265-64252e71924b)
![unistall-github](https://github.com/Appu26J/Softuninstall/assets/150511635/cb500c2a-7f9f-4021-80f6-dbbb329bf706)
The .exe is exists.
![image](https://github.com/Appu26J/Softuninstall/assets/150511635/ec5ca4d6-c0f0-44e8-bd18-6577d82e4f2e)

**Comment by Appu26J** [comment]
well that's weird, if you launch that exe yourself does it work?
